plugin: amazon.aws.aws_ec2

regions:
  - us-west-1

# Attach the default AWS profile
aws_profile: default

filters:
  instance-state-name: running
  tag:Cluster: kube1

# By default, the inventory will only return the first match
hostnames:
  # Use dns-name attribute as hostname
  - dns-name

  # This option allows displaying the public ip addresses.
  #- ip-address

groups:
  control: "'control' in tags.Role"
  workers: "'worker' in tags.Role"


compose:
  ansible_ssh_private_key_file: ssh-key/kube-access.pem
  ansible_host: dns-name

  # Host variables that are strings need to be wrapped with two sets of quotes.
  # See https://docs.ansible.com/ansible/latest/plugins/inventory.html#using-inventory-plugins for details.
  ansible_user: '"ubuntu"'
  pod_cidr: '"10.245.0.0/16"'

